Finalized home screen and implemented game detailed page
cuappdev/score-ios pull request #3
Opened 2024-10-23 22:11 UTC by AdelynnWu

## Overview

Finalized home screen and implemented the game detailed views at different game statuses (the game hasn't started/live now).

## Changes Made

### Change 1
Added fonts to Constants

### Change 2
Added UpcomingCardView and implemented the carousel in the home view

### Change 3
Implemented noGameView and adjusted logic in contentView (noGameView shows up when there are no upcoming games)

### Change 4
Added GameView (game detailed page when the game hasn't started) and GameDetailedScoreView (game started)

## Next Steps
Factor out duplicate code in GameView and GameDetailedScoreView

2024-10-24 03:06 UTC, caitlynjin commented on score-ios/Models/Game.swift
> +// polo, rowing, equestrian, sprint football
Not sure if this comment is meant to stay here?

2024-10-24 03:09 UTC, caitlynjin commented on score-ios/Views/FilterTile.swift
> +
```suggestion
```

2024-10-24 03:10 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +
```suggestion
```

2024-10-24 03:13 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +
```suggestion
```

2024-10-24 03:16 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                    .background(Color(red: 179 / 255, green: 27 / 255, blue: 27 / 255))
Let's keep colors in Constants instead for styling purposes

2024-10-24 03:20 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                    // navigate to score summary view
```suggestion
                    // TODO: navigate to score summary view
```

2024-10-24 03:21 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +
```suggestion
```

2024-10-24 03:22 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +//            .padding(.top, 50)
```suggestion
```

2024-10-24 03:23 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                    .font(.system(size: 27, weight: .regular))
Same thing with fonts, we should store them in Constants for consistent styling across the app

2024-10-24 03:23 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                        // Add action for back button
```suggestion
                        // TODO: Add action for back button
```

2024-10-24 03:23 UTC, caitlynjin commented on score-ios/Views/GameTile.swift
> +
```suggestion
```

2024-10-24 03:24 UTC, caitlynjin commented on score-ios/Views/GameTile.swift
>                  }   .padding(.trailing, 20)
```suggestion
                }   
                .padding(.trailing, 20)
```

2024-10-24 03:25 UTC, caitlynjin commented on score-ios/Views/GameTile.swift
> +
I would add a TODO here

2024-10-24 03:26 UTC, caitlynjin commented on score-ios/Views/GameView.swift
> +                        // action
```suggestion
                        // TODO: action
```

2024-10-24 03:26 UTC, caitlynjin commented on score-ios/Views/GameView.swift
> +                        // Add action for back button
```suggestion
                        // TODO: Add action for back button
```

2024-10-24 03:27 UTC, caitlynjin commented on score-ios/Views/NoGameView.swift
> +                    .foregroundStyle(Constants.Colors.gray_text).padding(.top, 2)
Keep modifiers on their own lines

2024-10-24 03:28 UTC, caitlynjin commented on score-ios/Views/NoGameView.swift
> +                Text("No games yet.").font(Constants.Fonts.bodyBold)
Move the font modifier to its own line

2024-10-24 03:29 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +
```suggestion
```

2024-10-24 03:29 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +
```suggestion
```

2024-10-24 03:30 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +                    VStack {
Remove empty VStack

2024-10-24 03:31 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +                                .fill(index == selectedCardIndex ? Constants.Colors.primary_red : Color(red: 194 / 255, green: 194 / 255, blue: 194 / 255, opacity: 1))
Same thing as above about colors in Constants

2024-10-24 03:31 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +
```suggestion
```

2024-10-24 03:32 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +                                }   .buttonStyle(PlainButtonStyle())
```suggestion
                                }   
                                .buttonStyle(PlainButtonStyle())
```

2024-10-24 03:32 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +                                } label : {
```suggestion
                                } label: {
```

2024-10-24 03:32 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +
```suggestion
```

2024-10-24 03:32 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
>              }   .padding(.leading, paddingMain)
```suggestion
            }   
            .padding(.leading, paddingMain)
```

2024-10-24 03:33 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +        }.onAppear {
Is this still being used?

2024-10-24 03:34 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +
```suggestion
```

2024-10-24 03:35 UTC, caitlynjin commented on score-ios/Views/ScoreSummaryTile.swift
> +    var score: String
Add a line space here

2024-10-24 03:36 UTC, caitlynjin commented on score-ios/Views/UpcomingCard.swift
> +
```suggestion
```

2024-10-24 03:37 UTC, caitlynjin commented on score-ios/Views/UpcomingCard.swift
> +                Color(red: 1 / 255, green: 31 / 255, blue: 91 / 255, opacity: 0.4)
I would add these colors to Constants as well since you're using this gradient pretty often

2024-10-24 03:38 UTC, caitlynjin commented on score-ios/Views/UpcomingCard.swift
> +struct UpcomingCard: View {
```suggestion
struct UpcomingCard: View {

```

2024-10-24 03:38 UTC, caitlynjin commented on score-ios/Views/ScoreSummaryTile.swift
> +struct ScoreSummaryTile: View {
```suggestion
struct ScoreSummaryTile: View {

```

2024-10-24 03:56 UTC, caitlynjin requested changes
Yayy great job on your PR! ✨ I made a few comments mostly about styling, so please take a look at them and request me again! Just to kind of summarize some main points:
- I would try to place any fonts, colors, etc into the Constants to keep styling consistent across the app and for easy access.
- Keep view modifiers on their own line, which also makes it easier to read.
- Pay attention to whitespace in your code! Generally I add an empty line in between views on the same level, but I would keep it consistent with the rest of the codebase though if it's not in that fashion.
- Another thing I noticed is that most of your code is in the body, which makes it tough to read! I would divide up your code into sections depending on what's being displayed. For example, you could create another computed property in this fashion:
  `private var information: some View`
  and add the chunks of code inside there, then call it inside your main `body` as `information`.

Sorry that was a lot of info! Please come up to me or DM me if you need any clarification or have any other questions :)

2024-10-30 20:24 UTC, AdelynnWu commented on score-ios/Views/GameDetailedScoreView.swift
> +                            .frame(width: 60, alignment: .leading)
I tried not setting it but then the alignment of the following columns will be off since the length of their first column are different.

2024-11-01 03:57 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +
```suggestion
```

2024-11-01 03:58 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +//        .padding(.trailing, 24)
```suggestion
```

2024-11-01 03:59 UTC, caitlynjin commented on score-ios/Views/ScoreApp.swift
> +                        FilterTile(sport: sport, selected: sport == selectedSport)
```suggestion
                            FilterTile(sport: sport, selected: sport == selectedSport)
```

2024-11-01 04:02 UTC, caitlynjin approved these changes
Awesome work! I think I may have missed a few things, but otherwise it looks great!

2024-11-10 17:12 UTC, daniel-chuang commented on score-ios/Models/Game.swift
Good changes for All, HW, LW. Not sure we should remove "Diving" though

2024-11-10 17:13 UTC, daniel-chuang commented on score-ios/Utils/Constants.swift
Nice work adding the fonts, the gradients are also good to have temporarily but I think we'll be getting those directly from Backend once thats up!

2024-11-10 20:17 UTC, merged