Integrated backend and fixed UI
cuappdev/score-ios pull request #4
Opened 2024-12-06 20:00 UTC by AdelynnWu

# Overview
Integrated backend into the app using Apollo-client and fixed filter and icon-rendering issues.

## Changes
### Change 1
Set up GraphQL schema and generated queries.

### Change 2 
Implemented functions in NetworkManager

### Change 3
Fixed filtering functions in HomeView and PastGameView

### Change 4
Updated icon image names

### Change 5 
Modified Game struct, added new Team struct, and implemented decoding initializers for all structs in model Game

2024-12-08 04:00 UTC, caitlynjin commented on score-ios/Data/NetworkManager.swift
> +//}()
Remove commented out code if not necessary.

2024-12-08 04:02 UTC, caitlynjin commented on score-ios/Data/NetworkManager.swift
> +//                    }
Remove commented out code if not necessary.

2024-12-08 04:02 UTC, caitlynjin commented on score-ios/Data/NetworkManager.swift
> +//                    print("game is empty: " + String(filteredGames.isEmpty))
Remove commented out code if not necessary.

2024-12-08 04:07 UTC, caitlynjin commented on score-ios/Utils/OrdinalSuffix.swift
> +}
Could you put these functions inside of a class called `OrdinalSuffix`?

2024-12-08 04:07 UTC, caitlynjin commented on score-ios/ViewModels/GamesViewModel.swift
> +    }
Remove if unused.

2024-12-08 04:10 UTC, caitlynjin commented on score-ios/ViewModels/GamesViewModel.swift
> +            let startOfToday = calendar.startOfDay(for: now)
I would combine these onto the `startOfToday` line, except for `twoHours`.

2024-12-08 04:11 UTC, caitlynjin commented on score-ios/ViewModels/GamesViewModel.swift
> +            let startOfToday = calendar.startOfDay(for: now)
Same as above comment.

2024-12-08 04:15 UTC, caitlynjin commented on score-ios/ViewModels/GamesViewModel.swift
> +    private func getUpcomingGames(allGames: [Game]) -> [Game] {
You might be able to make this code more concise by using the filter and sort function on the `allGames` array. I believe you can filter the games today, then sort by their dates (assuming that's what your array looks like).

2024-12-08 04:16 UTC, caitlynjin commented on score-ios/ViewModels/GamesViewModel.swift
> +    private func getPastGames(allGames: [Game]) -> [Game] {
Same idea with this function - use the filter function!

2024-12-08 04:17 UTC, caitlynjin commented on score-ios/ViewModels/GamesViewModel.swift
> +//}
For all of the above commented lines, delete if they're unused, or leave a TODO: with some comments about it.

2024-12-08 04:18 UTC, caitlynjin commented on score-ios/Views/FilterTile.swift
> +//                .foregroundStyle(selected ? Constants.Colors.selected : Constants.Colors.iconGray)
Remove if unused.

2024-12-08 04:18 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                    .padding(.trailing, 24)
```suggestion
                    .padding(.trailing, 24)
                    
```

2024-12-08 04:20 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                .font(Constants.Fonts.medium14)
```suggestion
                .font(Constants.Fonts.medium14)
                
```

2024-12-08 04:21 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                    .frame(width: 13, height: 19)
```suggestion
                    .frame(width: 13, height: 19)
                    
```

2024-12-08 04:21 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
>                  Text("Ithaca (Schoellkopf)")
```suggestion
                Text("Ithaca (Schoellkopf)")
                
```

2024-12-08 04:21 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                    .frame(width: 19.78, height: 18.34)
```suggestion
                    .frame(width: 19.78, height: 18.34)
                    
```

2024-12-08 04:22 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                    .font(Constants.Fonts.gameText)
Place empty lines in between views.

2024-12-08 04:22 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +                        .font(Constants.Fonts.buttonLabel)
Place empty lines in between views.

2024-12-08 04:24 UTC, caitlynjin commented on score-ios/Views/GameDetailedScoreView.swift
> +            }) {
Can you use the standard Button format:
`Button {
// Action
} label: {
// UI
}`

2024-12-08 04:26 UTC, caitlynjin commented on score-ios/Views/GameTile.swift
> +//                    Image(game.opponent)
Remove comment.

2024-12-08 04:27 UTC, caitlynjin commented on score-ios/Views/HomeView.swift
> +    @State private var errorMessage: String?
Could you make these alphabetical order?

2024-12-08 04:29 UTC, caitlynjin commented on score-ios/Views/HomeView.swift
> +// MARK: Functions
All of this code would make more sense in a ViewModel, could you move this to the HomeViewModel?

2024-12-08 04:32 UTC, caitlynjin commented on score-ios/Views/HomeView.swift
> +                        FilterTile(sport: sport, selected: sport == selectedSport)
```suggestion
                            FilterTile(sport: sport, selected: sport == selectedSport)
```

2024-12-08 04:32 UTC, caitlynjin commented on score-ios/Views/HomeView.swift
> +                ) { game in
Place these on the same line.

2024-12-08 04:34 UTC, caitlynjin commented on score-ios/Views/MainTabView.swift
> +
```suggestion
```

2024-12-08 04:34 UTC, caitlynjin commented on score-ios/Views/PastGameCard.swift
> +    var game: Game
```suggestion
    var game: Game
    
```

2024-12-08 04:35 UTC, caitlynjin commented on score-ios/Views/PastGameCard.swift
> +            .frame(width: 64, height: 64)
Add an indent.

2024-12-08 04:35 UTC, caitlynjin commented on score-ios/Views/PastGameCard.swift
> +                    .frame(width: 25, height: 25)
Empty lines in between views.

2024-12-08 04:36 UTC, caitlynjin commented on score-ios/Views/PastGameCard.swift
> +                    .foregroundStyle(.gray)
Empty lines in between views.

2024-12-08 04:37 UTC, caitlynjin commented on score-ios/Views/PastGameTile.swift
>      var body: some View {
This is quite a big code section, could you separate these into separate variables?

2024-12-08 04:38 UTC, caitlynjin commented on score-ios/Views/PastGameTile.swift
> +
Is there something that's supposed to be here?

2024-12-08 04:38 UTC, caitlynjin commented on score-ios/Views/PastGameView.swift
> +
```suggestion
```

2024-12-08 04:38 UTC, caitlynjin commented on score-ios/Views/PastGameView.swift
> +    @EnvironmentObject var viewModel: GamesViewModel
Alphabetical order please :)

2024-12-08 04:39 UTC, caitlynjin commented on score-ios/Views/PastGameView.swift
> +// MARK: Functions
These functions would go in the view model as well. Then you would call it by calling `viewModel.fetchPastGames()`.

2024-12-08 04:41 UTC, caitlynjin commented on score-ios/Views/PastGameView.swift
> +                        FilterTile(sport: sport, selected: sport == selectedSport)
```suggestion
                            FilterTile(sport: sport, selected: sport == selectedSport)
```

2024-12-08 04:42 UTC, caitlynjin commented on score-ios/Views/PastGameView.swift
> +    }
In general in this view, I see lots of duplicate code that is used elsewhere - could you create files that hold those views so that you can reuse them? e.g. a Carousel file that contains a Carousel view.

2024-12-08 04:44 UTC, caitlynjin commented on score-ios/Views/ScoringSummary.swift
> +struct ScoringUpdateCell : View {
Create another file for this struct.

2024-12-08 04:45 UTC, caitlynjin commented on score-ios/Views/ScoringSummary.swift
> +                .resizable().frame(width: 32, height: 32)
```suggestion
                    .resizable().frame(width: 32, height: 32)
```

2024-12-08 04:45 UTC, caitlynjin commented on score-ios/Views/ScoringSummary.swift
> +        .padding(.bottom, 12)
You can use .horizontal and .vertical to make these more concise.

2024-12-08 04:45 UTC, caitlynjin commented on score-ios/Views/TabViewIcon.swift
> +       private let tabItems = ["schedule", "scoreboard"]
Indentation is off here.

2024-12-08 04:46 UTC, caitlynjin commented on score-ios/Views/TabViewIcon.swift
> +                            .foregroundStyle(itemIndex == selectionIndex ? Constants.Colors.primary_red : Constants.Colors.unselectedText)
Empty line in between views.

2024-12-08 04:46 UTC, caitlynjin commented on score-ios/Views/UpcomingCard.swift
> +                image in
Place on the same line.

2024-12-08 04:46 UTC, caitlynjin commented on score-ios/Views/UpcomingCard.swift
> +                AsyncImage(url: URL(string: game.opponent.image)) {image in
```suggestion
                AsyncImage(url: URL(string: game.opponent.image)) { image in
```

2024-12-08 04:50 UTC, caitlynjin requested changes
Awesome PR Adelynn!! There's a few styling comments I'd like you to address, as well as making some functions that filter/sort games, etc more concise. Please let me know if you have any specific questions :)

2025-02-05 22:20 UTC, daniel-chuang reviewed
awesome

2025-02-05 23:32 UTC, closed without merging